
export type Destaque = {
  id: string;
  Codigo: string;
  ValorIptu: string;
  ValorCondominio: string;
  Categoria: string;
  AreaTerreno: number;
  Bairro: string;
  GMapsLatitude: string;
  GMapsLongitude: string;
  Cidade: string;
  ValorVenda: number;
  ValorLocacao: number;
  Dormitorios: string;
  Suites: string;
  Vagas: string;
  AreaTotal: number;
  Descricao: string;
  DataHoraAtualizacao: Date;
  Lancamento: string;
  Status: string;
  Empreendimento: string;
  Endereco: string;
  Numero: string;
  Complemento: string;
  UF: string;
  CEP: string;
  DestaqueWeb: string;
  FotoDestaque: string;
  Latitude: string;
  Longitude: string;
  FotoDestaqueEmpreendimento: string;
  VideoDestaque: string;
  corretorId: string;
};